### ISSUE TITLE
Questions on Main() function in marmitek-gw/marmitek/gateway.py

### ISSUE THREAD

**Issue by LaureCremieux** [pawmint/marmitek-gw#2]
# Main() function in marmitek-gw/marmitek/gateway.py

Two things here, that I'm not sure to understand:
* the position of the data['house'] = gate.find_house(data['sensor']) 
* the story of the house prefix

So here it starts:

```
for data in mochad_reader.run(gate.timezone): 
```
if data format not recognized, find house corresponding to the sensor → what for? Useless here, should be in the Else:
```
       if data['type'] != 'error':
           try:  
               data['house'] = gate.find_house(data['sensor']) 
           except KeyError:
               logger.warning("Unknown sensor: %s" % data['sensor'])
```
else if data format recognized, define house prefix:
```
           else:
```
* If it's a door signal, find the house it comes from and save the house prefix, for example, prefix = 'house2'
```
               if data['sensorKind'] == 'door': 
                   for house in gate.config['houses']: 
                       if house['id'] == data['house']: #data['house'] not defined here
                           prefix = house['prefix'] 
                           break
```
* If it's not a door signal, save prefix = ''
```
                   else:
                       prefix = ''
```

Then append prefix to data['sensor'] → why add the house prefix to door sensors only? I guess because the house prefix is already notified in the pattern for motion sensors, but not for door sensors? (Patterns are hard to read)
```
                   data['sensor'] = prefix.lower() + data['sensor']
```

As a result, 
* if signal comes from door sensor, the sensor is : 'house2_doorsensor1' 
* if signal comes from motion sensor, the sensor is 'motionsensor4' 

Creates the topic name and pushes it 
```
               topic = "/marmitek/sensor/%s" % data['sensor'] 
               gate.push(data['house'], topic, data) 
```

Thanks!

**Comment by RomainEndelin** [comment]
I'll answer your last question first:
Door sensors have a random 6-characters code, which doesn't give us any indication on the house, so we want to prepend the house code (like A112233). On the other hand, motion sensors can be configured in the hardware to have a code like A1, E2, etc, so we give the house code at the hardware layer.

For your first question, I think you missed a point, check again the indentation: the `else` is at the same level as the `try`. In python you can put a `else` after some `except`, meaning "else, if there was no exception".
Read the code again from that point of view and it should make sense ;)

Feel free to close the issue if you understand.

**Comment by LaureCremieux** [comment]
ok got it! thanks, I didn't know you could write an else after the except :)
